import { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { AlertTriangle, ChevronLeft, ChevronRight, GitCommitHorizontal, MoreHorizontal, MoreVertical, Trash2, PanelLeft, X } from 'lucide-react';
import { CollectedDataPanel } from './components/CollectedDataPanel';
import { TILEditor } from './components/TILEditor';
import { useTilPageLogic } from './hooks/useTilPageLogic';
import { TILModeTabs, type TILMode } from './components/TILModeTabs';
import type { TilResponse } from '@san/shared';

export function TilPage() {
    const [searchParams] = useSearchParams();
    const {
        selectedDate,
        setSelectedDate,
        title,
        setTitle,
        draft,
        tilList,
        selectedSummaryId,
        setSelectedSummaryId,
        selectedTil,
        tilQuery,
        sourcesQuery,
        generationStatusQuery,
        commitStatusQuery,
        generateMutation,
        updateMutation,
        deleteMutation,
        commitMutation,
        generationTone,
        generationMessage,
        commitMessage,
    } = useTilPageLogic();

    const [activeTab, setActiveTab] = useState<TILMode>('drafts');
    const [isTilListOpen, setIsTilListOpen] = useState(false);
    const [openTilMenuId, setOpenTilMenuId] = useState<string | null>(null);
    const [isTitleMenuOpen, setIsTitleMenuOpen] = useState(false);
    const [isCalendarOpen, setIsCalendarOpen] = useState(false);
    const [calendarMonth, setCalendarMonth] = useState(() => startOfMonth(parseDateString(selectedDate)));
    const [pendingDeleteTilId, setPendingDeleteTilId] = useState<string | null>(null);
    const dateLabel = formatDateForDisplay(selectedDate);
    const dateParam = searchParams.get('date');

    useEffect(() => {
        if (!isValidDateParam(dateParam) || dateParam === selectedDate) return;
        setSelectedDate(dateParam);
    }, [dateParam, selectedDate, setSelectedDate]);

    useEffect(() => {
        setOpenTilMenuId(null);
        setIsTitleMenuOpen(false);
        setIsCalendarOpen(false);
        setCalendarMonth(startOfMonth(parseDateString(selectedDate)));
    }, [selectedDate]);

    useEffect(() => {
        if (!openTilMenuId && !isTitleMenuOpen && !isCalendarOpen) return;

        const handlePointerDown = () => {
            setOpenTilMenuId(null);
            setIsTitleMenuOpen(false);
            setIsCalendarOpen(false);
        };
        const handleKeyDown = (event: KeyboardEvent) => {
            if (event.key === 'Escape') {
                setOpenTilMenuId(null);
                setIsTitleMenuOpen(false);
                setIsCalendarOpen(false);
            }
        };

        document.addEventListener('pointerdown', handlePointerDown);
        document.addEventListener('keydown', handleKeyDown);

        return () => {
            document.removeEventListener('pointerdown', handlePointerDown);
            document.removeEventListener('keydown', handleKeyDown);
        };
    }, [openTilMenuId, isTitleMenuOpen, isCalendarOpen]);

    const goToPrevDate = () => {
        const date = new Date(selectedDate);
        date.setDate(date.getDate() - 1);
        setSelectedDate(shiftDate(date));
    };

    const latestGeneratedTilDate = getLatestAutoGeneratedTilDate();
    const isLatestGeneratedTilDate = selectedDate >= latestGeneratedTilDate;
    const latestGeneratedMonth = startOfMonth(parseDateString(latestGeneratedTilDate));
    const calendarDays = getCalendarDays(calendarMonth);

    const goToNextDate = () => {
        if (isLatestGeneratedTilDate) return;
        const date = new Date(selectedDate);
        date.setDate(date.getDate() + 1);
        setSelectedDate(shiftDate(date));
    };

    const isCommitting =
        commitMutation.isPending ||
        commitStatusQuery.data?.status === 'PENDING' ||
        commitStatusQuery.data?.status === 'PROCESSING';
    const displayedTitle = activeTab === 'drafts' ? selectedTil?.title ?? title : title;

    const requestDeleteTil = (summaryId = selectedTil?.summaryId) => {
        if (!summaryId || deleteMutation.isPending) return;

        setOpenTilMenuId(null);
        setIsTitleMenuOpen(false);
        setPendingDeleteTilId(summaryId);
    };

    const confirmDeleteTil = () => {
        if (!pendingDeleteTilId || deleteMutation.isPending) return;

        deleteMutation.mutate(pendingDeleteTilId, {
            onSettled: () => setPendingDeleteTilId(null),
        });
    };

    return (
        <section className="flex h-auto w-full flex-col overflow-hidden bg-background text-text-primary lg:h-[calc(100vh-80px)] lg:flex-row">
            <div className="no-scrollbar order-1 flex min-w-0 flex-1 flex-col overflow-y-auto px-2 pb-6 pt-3 md:px-3 lg:order-1">
                <header className="mb-6 flex flex-col gap-3">
                    <h1 className="flex items-baseline gap-1 text-2xl font-extrabold tracking-tight">
                        <span className="text-primary-signal">T</span>
                        <span className="bg-gradient-to-r from-white via-white/90 to-white/40 bg-clip-text text-transparent">oday</span>
                        <span className="ml-2 text-primary-signal">I</span>
                        <span className="ml-2 text-primary-signal">L</span>
                        <span className="bg-gradient-to-r from-white via-white/90 to-white/40 bg-clip-text text-transparent">earned</span>
                    </h1>

                    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-center">
                        <div className="flex items-center gap-4">
                            <div
                                className="relative flex items-center gap-1 px-1.5 py-1"
                                onPointerDown={(event) => event.stopPropagation()}
                            >
                                <button
                                    type="button"
                                    onClick={goToPrevDate}
                                    className="rounded p-0.5 text-text-secondary transition-colors hover:text-white"
                                    aria-label="이전 날짜"
                                >
                                    <ChevronLeft size={14} />
                                </button>
                                <button
                                    type="button"
                                    onClick={() => {
                                        setIsCalendarOpen((current) => !current);
                                        setOpenTilMenuId(null);
                                        setIsTitleMenuOpen(false);
                                    }}
                                    className="flex min-w-[118px] items-center justify-center px-1.5 py-0.5 text-center text-sm font-semibold tracking-wide text-white"
                                    aria-expanded={isCalendarOpen}
                                >
                                    {dateLabel}
                                </button>
                                <button
                                    type="button"
                                    onClick={goToNextDate}
                                    disabled={isLatestGeneratedTilDate}
                                    className="rounded p-0.5 text-text-secondary transition-colors hover:text-white disabled:cursor-not-allowed disabled:opacity-25"
                                    aria-label="다음 날짜"
                                >
                                    <ChevronRight size={14} />
                                </button>

                                {isCalendarOpen ? (
                                    <div className="absolute left-0 top-11 z-40 w-[260px] rounded-[24px] border border-white/12 bg-surface-lowest/82 p-3 shadow-[0_24px_70px_rgba(0,0,0,0.46),inset_0_1px_0_rgba(255,255,255,0.08)] backdrop-blur-2xl">
                                        <div className="mb-3 flex items-center justify-between">
                                            <button
                                                type="button"
                                                onClick={() => setCalendarMonth((current) => shiftMonth(current, -1))}
                                                className="flex h-7 w-7 items-center justify-center rounded-lg text-text-secondary transition-colors hover:bg-white/8 hover:text-white"
                                                aria-label="이전 달"
                                            >
                                                <ChevronLeft size={15} />
                                            </button>
                                            <span className="text-sm font-bold text-white">
                                                {formatCalendarMonth(calendarMonth)}
                                            </span>
                                            <button
                                                type="button"
                                                onClick={() => setCalendarMonth((current) => shiftMonth(current, 1))}
                                                disabled={calendarMonth >= latestGeneratedMonth}
                                                className="flex h-7 w-7 items-center justify-center rounded-lg text-text-secondary transition-colors hover:bg-white/8 hover:text-white disabled:cursor-not-allowed disabled:opacity-30"
                                                aria-label="다음 달"
                                            >
                                                <ChevronRight size={15} />
                                            </button>
                                        </div>

                                        <div className="grid grid-cols-7 gap-0.5 text-center text-[10px] font-bold uppercase tracking-wider text-text-secondary/60">
                                            {['일', '월', '화', '수', '목', '금', '토'].map((day) => (
                                                <span key={day} className="py-1">{day}</span>
                                            ))}
                                        </div>

                                        <div className="mt-1 grid grid-cols-7 gap-0.5">
                                            {calendarDays.map((day) => {
                                                const dayValue = shiftDate(day);
                                                const isCurrentMonth = day.getMonth() === calendarMonth.getMonth();
                                                const isSelected = dayValue === selectedDate;
                                                const isDisabled = dayValue > latestGeneratedTilDate;

                                                return (
                                                    <button
                                                        key={dayValue}
                                                        type="button"
                                                        onClick={() => {
                                                            if (isDisabled) return;
                                                            setSelectedDate(dayValue);
                                                            setIsCalendarOpen(false);
                                                        }}
                                                        disabled={isDisabled}
                                                        className={`flex h-7 items-center justify-center rounded-lg text-xs font-semibold transition-colors ${
                                                            isSelected
                                                                ? 'bg-primary-signal text-background'
                                                                : isCurrentMonth
                                                                    ? 'text-white hover:bg-white/10'
                                                                    : 'text-text-secondary/35 hover:bg-white/5'
                                                        } disabled:cursor-not-allowed disabled:text-text-secondary/20 disabled:hover:bg-transparent`}
                                                    >
                                                        {day.getDate()}
                                                    </button>
                                                );
                                            })}
                                        </div>
                                    </div>
                                ) : null}
                            </div>

                            <div className="hidden h-4 w-px bg-white/10 md:block" />
                        </div>

                        <div className="flex flex-wrap items-center gap-3">
                            <TILModeTabs activeTab={activeTab} onChange={setActiveTab} />

                            <button
                                type="button"
                                onClick={() => selectedTil && commitMutation.mutate(selectedTil.summaryId)}
                                disabled={isCommitting || !selectedTil}
                                className="flex h-9 flex-1 items-center justify-center gap-2 rounded-bl-md rounded-br-[14px] rounded-tl-[14px] rounded-tr-md bg-[#238636] px-4 text-sm font-medium text-white transition-colors hover:bg-[#2ea043] disabled:cursor-not-allowed disabled:opacity-50 md:flex-none"
                            >
                                <GitCommitHorizontal size={15} />
                                {isCommitting ? 'Committing...' : 'Commit'}
                            </button>
                        </div>
                    </div>
                </header>

                <div className="flex min-h-0 flex-1 gap-2">
                    <div className="flex min-h-0 shrink-0 items-start gap-1.5">
                        <button
                            type="button"
                            onClick={() => {
                                setIsTilListOpen((current) => !current);
                                setOpenTilMenuId(null);
                            }}
                            className={`flex h-8 w-8 shrink-0 items-center justify-center text-text-secondary transition ${
                                isTilListOpen
                                    ? 'text-white'
                                    : 'hover:text-primary-signal'
                            }`}
                            aria-label="Toggle TIL list"
                            aria-expanded={isTilListOpen}
                        >
                            <PanelLeft size={19} />
                        </button>

                        <aside
                            className={`min-h-[500px] overflow-hidden transition-[width,border-color] duration-300 ease-out ${
                                isTilListOpen
                                    ? 'w-[260px] border-r border-white/10'
                                    : 'w-0 border-r-0 border-transparent'
                            }`}
                            aria-hidden={!isTilListOpen}
                        >
                            <div className="w-[260px]">
                                <div className={`no-scrollbar max-h-[calc(100vh-230px)] overflow-y-auto px-2 pb-3 transition-opacity duration-150 ${
                                    isTilListOpen ? 'opacity-100 delay-100' : 'pointer-events-none opacity-0'
                                }`}>
                                    {tilQuery.isPending ? (
                                        <div className="px-3 py-4 text-sm text-text-secondary">Loading...</div>
                                    ) : tilList.length === 0 ? (
                                        <div className="px-3 py-4 text-sm text-text-secondary">No TILs for this date.</div>
                                    ) : (
                                        tilList.map((til, index) => {
                                            const isSelected = til.summaryId === (selectedSummaryId ?? selectedTil?.summaryId);

                                            return (
                                                <div key={til.summaryId} className="group relative">
                                                    <button
                                                        type="button"
                                                        onClick={() => {
                                                            setSelectedSummaryId(til.summaryId);
                                                            setOpenTilMenuId(null);
                                                        }}
                                                        className={`flex w-full items-start gap-3 rounded-xl px-3 py-3 pr-9 text-left transition ${
                                                            isSelected
                                                                ? 'bg-white/[0.075] text-white'
                                                                : 'text-text-secondary hover:bg-white/5 hover:text-white'
                                                        }`}
                                                    >
                                                        <span className="min-w-0">
                                                            <span className="block truncate text-sm font-semibold">
                                                                {getTilTitle(til, index)}
                                                            </span>
                                                            <span className="mt-1 block text-xs text-text-secondary/70">
                                                                {formatTimeForDisplay(til.updatedAt)}
                                                            </span>
                                                        </span>
                                                    </button>

                                                    <button
                                                        type="button"
                                                        onClick={(event) => {
                                                            event.stopPropagation();
                                                            setOpenTilMenuId((current) => current === til.summaryId ? null : til.summaryId);
                                                        }}
                                                        aria-label="Open TIL actions"
                                                        aria-expanded={openTilMenuId === til.summaryId}
                                                        className={`absolute right-2 top-2 flex h-7 w-7 items-center justify-center rounded-full text-text-secondary transition ${
                                                            openTilMenuId === til.summaryId
                                                                ? 'text-text-secondary'
                                                                : 'opacity-0 hover:text-white group-hover:opacity-100'
                                                        }`}
                                                    >
                                                        <MoreVertical size={15} strokeWidth={2.4} />
                                                    </button>

                                                    {openTilMenuId === til.summaryId ? (
                                                        <div
                                                            className="absolute right-2 top-10 z-30 w-32 overflow-hidden rounded-xl border border-white/12 bg-surface-lowest/78 p-1 shadow-[0_18px_48px_rgba(0,0,0,0.38),inset_0_1px_0_rgba(255,255,255,0.08)] backdrop-blur-xl"
                                                            onPointerDown={(event) => event.stopPropagation()}
                                                        >
                                                            <button
                                                                type="button"
                                                                onClick={(event) => {
                                                                    event.stopPropagation();
                                                                    requestDeleteTil(til.summaryId);
                                                                }}
                                                                disabled={deleteMutation.isPending}
                                                                className="flex h-9 w-full items-center gap-2 rounded-lg px-2.5 text-sm font-medium text-text-secondary transition-colors hover:bg-red-500/12 hover:text-red-300 disabled:cursor-not-allowed disabled:opacity-40"
                                                            >
                                                                <Trash2 size={14} strokeWidth={2.2} />
                                                                삭제
                                                            </button>
                                                        </div>
                                                    ) : null}
                                                </div>
                                            );
                                        })
                                    )}
                                </div>
                            </div>
                        </aside>
                    </div>

                    <div className="flex min-w-0 flex-1 flex-col gap-4">
                        <div className="px-1">
                            <h2 className="mb-1 text-[10px] font-bold uppercase tracking-widest text-primary-signal opacity-80">
                                # Today's Knowledge Summary
                            </h2>

                            <div className="relative flex items-start gap-3">
                                <textarea
                                    value={displayedTitle}
                                    onChange={(e) => setTitle(e.target.value)}
                                    onKeyDown={(e) => {
                                        if (e.key === 'Enter') e.preventDefault();
                                    }}
                                    placeholder="제목을 입력하세요"
                                    readOnly={activeTab !== 'edit'}
                                    rows={2}
                                    className="min-w-0 flex-1 resize-none overflow-hidden bg-transparent text-xl font-extrabold leading-7 text-white outline-none transition-all placeholder:text-text-secondary/20 focus:placeholder:text-text-secondary/10"
                                />

                                <div className="relative shrink-0">
                                    <button
                                        type="button"
                                        onClick={(event) => {
                                            event.stopPropagation();
                                            setIsTitleMenuOpen((current) => !current);
                                            setOpenTilMenuId(null);
                                        }}
                                        disabled={deleteMutation.isPending || !selectedTil}
                                        title="TIL actions"
                                        aria-label="TIL actions"
                                        aria-expanded={isTitleMenuOpen}
                                        className={`flex h-9 w-9 items-center justify-center rounded-xl transition-colors disabled:cursor-not-allowed disabled:opacity-35 ${
                                            isTitleMenuOpen
                                                ? 'text-text-secondary'
                                                : 'text-text-secondary hover:text-white'
                                        }`}
                                    >
                                        <MoreHorizontal size={18} strokeWidth={2.4} />
                                    </button>

                                    {isTitleMenuOpen ? (
                                        <div
                                            className="absolute right-0 top-10 z-30 w-40 overflow-hidden rounded-xl border border-white/12 bg-surface-lowest/82 p-1.5 shadow-[0_16px_42px_rgba(0,0,0,0.36),inset_0_1px_0_rgba(255,255,255,0.08)] backdrop-blur-xl"
                                            onPointerDown={(event) => event.stopPropagation()}
                                        >
                                        <button
                                            type="button"
                                            onClick={(event) => {
                                                event.stopPropagation();
                                                requestDeleteTil();
                                            }}
                                            disabled={deleteMutation.isPending || !selectedTil}
                                            className="flex h-9 w-full items-center gap-2.5 rounded-lg px-2.5 text-sm font-semibold text-text-secondary transition-colors hover:bg-red-500/12 hover:text-red-300 disabled:cursor-not-allowed disabled:opacity-40"
                                        >
                                            <Trash2 size={14} strokeWidth={2.2} />
                                            삭제
                                        </button>
                                        </div>
                                    ) : null}
                                </div>
                            </div>
                        </div>

                        <div className="flex min-h-[500px] flex-1 flex-col overflow-hidden rounded-2xl border border-white/5 bg-surface-lowest shadow-2xl">
                            <TILEditor
                                activeTab={activeTab}
                                title={title}
                                setTitle={setTitle}
                                draft={draft}
                                selectedTil={selectedTil}
                                isTilLoading={tilQuery.isPending}
                                generateMutation={generateMutation}
                                updateMutation={updateMutation}
                                commitMutation={commitMutation}
                                generationStatusQuery={generationStatusQuery}
                                commitStatusQuery={commitStatusQuery}
                                generationTone={generationTone}
                                generationMessage={generationMessage}
                                commitMessage={commitMessage}
                            />
                        </div>
                    </div>
                </div>
            </div>

            <aside className="no-scrollbar w-full lg:w-[360px] shrink-0 border-t lg:border-t-0 lg:border-l border-white/10 bg-transparent order-2 lg:order-2">
                <CollectedDataPanel sourcesQuery={sourcesQuery} selectedTil={selectedTil} />
            </aside>

            {pendingDeleteTilId ? (
                <div
                    className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 px-4 backdrop-blur-sm"
                    onPointerDown={() => {
                        if (!deleteMutation.isPending) setPendingDeleteTilId(null);
                    }}
                >
                    <div
                        className="w-full max-w-[360px] rounded-2xl border border-white/12 bg-surface-lowest/82 p-5 shadow-[0_24px_80px_rgba(0,0,0,0.48),inset_0_1px_0_rgba(255,255,255,0.08)] backdrop-blur-2xl"
                        onPointerDown={(event) => event.stopPropagation()}
                    >
                        <div className="flex items-start justify-between gap-4">
                            <div className="flex items-start gap-3">
                                <span className="mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-error/12 text-error">
                                    <AlertTriangle size={18} strokeWidth={2.2} />
                                </span>
                                <div>
                                    <h2 className="text-base font-bold text-white">TIL을 삭제할까요?</h2>
                                    <p className="mt-2 text-sm leading-relaxed text-text-secondary">
                                        삭제한 TIL은 되돌릴 수 없습니다.
                                    </p>
                                </div>
                            </div>
                            <button
                                type="button"
                                onClick={() => setPendingDeleteTilId(null)}
                                disabled={deleteMutation.isPending}
                                className="rounded-full p-1 text-text-secondary transition-colors hover:bg-white/8 hover:text-white disabled:cursor-not-allowed disabled:opacity-40"
                                aria-label="닫기"
                            >
                                <X size={17} />
                            </button>
                        </div>

                        <div className="mt-6 flex justify-end gap-2">
                            <button
                                type="button"
                                onClick={() => setPendingDeleteTilId(null)}
                                disabled={deleteMutation.isPending}
                                className="h-9 rounded-lg px-4 text-sm font-semibold text-text-secondary transition-colors hover:bg-white/8 hover:text-white disabled:cursor-not-allowed disabled:opacity-40"
                            >
                                취소
                            </button>
                            <button
                                type="button"
                                onClick={confirmDeleteTil}
                                disabled={deleteMutation.isPending}
                                className="flex h-9 items-center gap-2 rounded-lg bg-error px-4 text-sm font-bold text-white transition-colors hover:bg-error/90 disabled:cursor-not-allowed disabled:opacity-60"
                            >
                                <Trash2 size={14} strokeWidth={2.2} />
                                {deleteMutation.isPending ? '삭제 중...' : '삭제'}
                            </button>
                        </div>
                    </div>
                </div>
            ) : null}
        </section>
    );
}

function formatDateForDisplay(dateString: string) {
    const date = new Date(dateString);

    return date.toLocaleDateString('ko-KR', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
    });
}

function formatCalendarMonth(date: Date) {
    return date.toLocaleDateString('ko-KR', {
        year: 'numeric',
        month: 'long',
    });
}

function formatTimeForDisplay(dateString: string) {
    const date = new Date(dateString);

    if (Number.isNaN(date.getTime())) return '';

    return date.toLocaleTimeString('ko-KR', {
        hour: '2-digit',
        minute: '2-digit',
    });
}
function getTilTitle(til: TilResponse, index: number) {
    return til.title?.trim() || `Untitled TIL ${index + 1}`;
}

function parseDateString(dateString: string) {
    const [year, month, day] = dateString.split('-').map(Number);
    return new Date(year, month - 1, day);
}

function startOfMonth(date: Date) {
    return new Date(date.getFullYear(), date.getMonth(), 1);
}

function shiftMonth(date: Date, months: number) {
    return new Date(date.getFullYear(), date.getMonth() + months, 1);
}

function getCalendarDays(monthDate: Date) {
    const firstDay = startOfMonth(monthDate);
    const start = new Date(firstDay);
    start.setDate(firstDay.getDate() - firstDay.getDay());

    return Array.from({ length: 42 }, (_, index) => {
        const date = new Date(start);
        date.setDate(start.getDate() + index);
        return date;
    });
}

function shiftDate(date: Date): string {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
}

function getLatestAutoGeneratedTilDate() {
    const date = new Date();
    date.setDate(date.getDate() - (date.getHours() < 3 ? 2 : 1));
    return shiftDate(date);
}

function isValidDateParam(value: string | null): value is string {
    if (!value || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return false;
    const date = new Date(value);
    return !Number.isNaN(date.getTime()) && shiftDate(date) === value;
}
