import { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { ChevronLeft, ChevronRight, GitCommitHorizontal, Trash2, PanelLeft } from 'lucide-react';
import { CollectedDataPanel } from './components/CollectedDataPanel';
import { TILEditor } from './components/TILEditor';
import { useTilPageLogic } from './hooks/useTilPageLogic';
import { TILModeTabs, type TILMode } from './components/TILModeTabs';

export function TilPage() {
    const [searchParams] = useSearchParams();
    const {
        selectedDate,
        setSelectedDate,
        title,
        setTitle,
        draft,
        setDraft,
        tilList,
        selectedSummaryId,
        setSelectedSummaryId,
        selectedTil,
        tilQuery,
        sourcesQuery,
        generationStatusQuery,
        commitStatusQuery,
        generateMutation,
        updateMutation,
        deleteMutation,
        commitMutation,
        generationTone,
        generationMessage,
        commitMessage,
    } = useTilPageLogic();

    const [activeTab, setActiveTab] = useState<TILMode>('drafts');
    const [isTilListOpen, setIsTilListOpen] = useState(false);
    const dateLabel = formatDateForDisplay(selectedDate);
    const dateParam = searchParams.get('date');

    useEffect(() => {
        if (!isValidDateParam(dateParam) || dateParam === selectedDate) return;
        setSelectedDate(dateParam);
    }, [dateParam, selectedDate, setSelectedDate]);

    const goToPrevDate = () => {
        const date = new Date(selectedDate);
        date.setDate(date.getDate() - 1);
        setSelectedDate(shiftDate(date));
    };

    const latestGeneratedTilDate = getLatestAutoGeneratedTilDate();
    const isLatestGeneratedTilDate = selectedDate >= latestGeneratedTilDate;

    const goToNextDate = () => {
        if (isLatestGeneratedTilDate) return;
        const date = new Date(selectedDate);
        date.setDate(date.getDate() + 1);
        setSelectedDate(shiftDate(date));
    };

    const isCommitting =
        commitMutation.isPending ||
        commitStatusQuery.data?.status === 'PENDING' ||
        commitStatusQuery.data?.status === 'PROCESSING';
    const displayedTitle = activeTab === 'edit' ? title : selectedTil?.title ?? title;

    const handleDeleteTil = () => {
        if (!selectedTil || deleteMutation.isPending) return;

        const confirmed = window.confirm('선택한 TIL을 삭제할까요? 삭제 후에는 되돌릴 수 없습니다.');
        if (!confirmed) return;

        deleteMutation.mutate(selectedTil.summaryId);
    };

    return (
        <section className="flex h-auto w-full flex-col overflow-hidden bg-background text-text-primary lg:h-[calc(100vh-80px)] lg:flex-row">
            <div className="no-scrollbar order-1 flex min-w-0 flex-1 flex-col overflow-y-auto px-4 pb-6 pt-3 md:px-6 lg:order-1">
                <header className="mb-6 flex flex-col gap-3">
                    <h1 className="flex items-baseline gap-1 text-2xl font-extrabold tracking-tight">
                        <span className="text-primary-signal">T</span>
                        <span className="bg-gradient-to-r from-white via-white/90 to-white/40 bg-clip-text text-transparent">oday</span>
                        <span className="ml-2 text-primary-signal">I</span>
                        <span className="ml-2 text-primary-signal">L</span>
                        <span className="bg-gradient-to-r from-white via-white/90 to-white/40 bg-clip-text text-transparent">earned</span>
                    </h1>

                    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-center">
                        <div className="flex items-center gap-4">
                            <div className="flex items-center gap-1 rounded-xl border border-white/5 bg-white/5 px-2 py-1.5">
                                <button
                                    type="button"
                                    onClick={goToPrevDate}
                                    className="rounded p-0.5 text-text-secondary transition-colors hover:text-white"
                                    aria-label="이전 날짜"
                                >
                                    <ChevronLeft size={14} />
                                </button>
                                <span className="min-w-[110px] text-center text-sm font-semibold tracking-wide text-white">
                                    {dateLabel}
                                </span>
                                <button
                                    type="button"
                                    onClick={goToNextDate}
                                    disabled={isLatestGeneratedTilDate}
                                    className="rounded p-0.5 text-text-secondary transition-colors hover:text-white disabled:cursor-not-allowed disabled:opacity-25"
                                    aria-label="다음 날짜"
                                >
                                    <ChevronRight size={14} />
                                </button>
                            </div>

                            <div className="hidden h-4 w-px bg-white/10 md:block" />
                        </div>

                        <div className="flex flex-wrap items-center gap-3">
                            <TILModeTabs activeTab={activeTab} onChange={setActiveTab} />

                            <button
                                type="button"
                                onClick={() => selectedTil && commitMutation.mutate(selectedTil.summaryId)}
                                disabled={isCommitting || !selectedTil}
                                className="flex h-10 flex-1 items-center justify-center gap-2 rounded-bl-md rounded-br-[14px] rounded-tl-[14px] rounded-tr-md bg-[#238636] px-4 text-sm font-medium text-white shadow-lg transition-all hover:bg-[#2ea043] hover:shadow-primary-signal/20 disabled:cursor-not-allowed disabled:opacity-50 md:h-11 md:flex-none"
                            >
                                <GitCommitHorizontal size={16} />
                                {isCommitting ? 'Committing...' : 'Commit'}
                            </button>
                        </div>
                    </div>
                </header>

                <div className="flex min-h-0 flex-1 gap-3">
                    <div className="flex min-h-0 shrink-0 items-start gap-2">
                        <button
                            type="button"
                            onClick={() => setIsTilListOpen((current) => !current)}
                            className={`flex h-8 w-8 shrink-0 items-center justify-center text-text-secondary transition ${
                                isTilListOpen
                                    ? 'text-white'
                                    : 'hover:text-primary-signal'
                            }`}
                            aria-label="Toggle TIL list"
                            aria-expanded={isTilListOpen}
                        >
                            <PanelLeft size={19} />
                        </button>

                        <aside
                            className={`min-h-[500px] overflow-hidden transition-[width,border-color] duration-300 ease-out ${
                                isTilListOpen
                                    ? 'w-[286px] border-r border-white/10'
                                    : 'w-0 border-r-0 border-transparent'
                            }`}
                            aria-hidden={!isTilListOpen}
                        >
                            <div className="w-[286px]">
                                <div className={`no-scrollbar max-h-[calc(100vh-230px)] overflow-y-auto px-3 pb-3 transition-opacity duration-150 ${
                                    isTilListOpen ? 'opacity-100 delay-100' : 'pointer-events-none opacity-0'
                                }`}>
                                    {tilQuery.isPending ? (
                                        <div className="px-3 py-4 text-sm text-text-secondary">Loading...</div>
                                    ) : tilList.length === 0 ? (
                                        <div className="px-3 py-4 text-sm text-text-secondary">No TILs for this date.</div>
                                    ) : (
                                        tilList.map((til, index) => {
                                            const isSelected = til.summaryId === (selectedSummaryId ?? selectedTil?.summaryId);

                                            return (
                                                <button
                                                    key={til.summaryId}
                                                    type="button"
                                                    onClick={() => {
                                                        setSelectedSummaryId(til.summaryId);
                                                    }}
                                                    className={`flex w-full items-start gap-3 rounded-xl px-3 py-3 text-left transition ${
                                                        isSelected
                                                            ? 'bg-white/[0.075] text-white'
                                                            : 'text-text-secondary hover:bg-white/5 hover:text-white'
                                                    }`}
                                                >
                                                    <span className="min-w-0">
                                                        <span className="block truncate text-sm font-semibold">
                                                            {getTilTitle(til, index)}
                                                        </span>
                                                        <span className="mt-1 block text-xs text-text-secondary/70">
                                                            {formatTimeForDisplay(til.updatedAt)}
                                                        </span>
                                                    </span>
                                                </button>
                                            );
                                        })
                                    )}
                                </div>
                            </div>
                        </aside>
                    </div>

                    <div className="flex min-w-0 flex-1 flex-col gap-4">
                        <div className="px-1">
                            <h2 className="mb-1 text-[10px] font-bold uppercase tracking-widest text-primary-signal opacity-80">
                                # Today's Knowledge Summary
                            </h2>

                        <div className="flex items-start gap-3">
                            <input
                                type="text"
                                value={displayedTitle}
                                onChange={(e) => setTitle(e.target.value)}
                                placeholder="제목을 입력하세요"
                                readOnly={activeTab !== 'edit'}
                                className="min-w-0 flex-1 bg-transparent text-xl font-extrabold text-white outline-none transition-all placeholder:text-text-secondary/20 focus:placeholder:text-text-secondary/10"
                            />

                            <button
                                type="button"
                                onClick={handleDeleteTil}
                                disabled={deleteMutation.isPending || !selectedTil}
                                className="mt-1 flex h-7 shrink-0 items-center justify-center gap-1 rounded-tl-[10px] rounded-br-[10px] rounded-bl-md rounded-tr-md bg-error px-2.5 text-[10px] font-bold text-white transition-colors hover:opacity-90 disabled:cursor-not-allowed disabled:bg-error/60"
                            >
                                <Trash2 size={12} strokeWidth={2.2} />
                                {deleteMutation.isPending ? 'DELETING' : 'DELETE'}
                            </button>
                        </div>
                    </div>
                            <input
                                type="text"
                                value={title}
                                onChange={(e) => setTitle(e.target.value)}
                                placeholder="제목을 입력하세요"
                                readOnly={activeTab === 'preview'}
                                className="w-full bg-transparent text-xl font-extrabold text-white outline-none transition-all placeholder:text-text-secondary/20 focus:placeholder:text-text-secondary/10"
                            />
                        </div>

                    <div className="flex min-h-[500px] flex-1 flex-col rounded-2xl border border-white/5 bg-surface-lowest shadow-2xl overflow-hidden">
                        <TILEditor
                            activeTab={activeTab}
                            title={title}
                            setTitle={setTitle}
                            draft={draft}
                            setDraft={setDraft}
                            selectedTil={selectedTil}
                            isTilLoading={tilQuery.isPending}
                            generateMutation={generateMutation}
                            updateMutation={updateMutation}
                            commitMutation={commitMutation}
                            generationStatusQuery={generationStatusQuery}
                            commitStatusQuery={commitStatusQuery}
                            generationTone={generationTone}
                            generationMessage={generationMessage}
                            commitMessage={commitMessage}
                        />
                    </div>
                </div>
            </div>

            <aside className="no-scrollbar w-full lg:w-[360px] shrink-0 border-t lg:border-t-0 lg:border-l border-white/10 bg-transparent order-2 lg:order-2">
                <CollectedDataPanel sourcesQuery={sourcesQuery} selectedTil={selectedTil} />
            </aside>
        </section>
    );
}

function formatDateForDisplay(dateString: string) {
    const date = new Date(dateString);

    return date.toLocaleDateString('ko-KR', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
    });
}

function formatTimeForDisplay(dateString: string) {
    const date = new Date(dateString);

    if (Number.isNaN(date.getTime())) return '';

    return date.toLocaleTimeString('ko-KR', {
        hour: '2-digit',
        minute: '2-digit',
    });
}
//
// function getTilTitle(til: TilResponse, index: number) {
//     return til.title?.trim() || `Untitled TIL ${index + 1}`;
// }

function shiftDate(date: Date): string {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
}

function getLatestAutoGeneratedTilDate() {
    const date = new Date();
    date.setDate(date.getDate() - (date.getHours() < 3 ? 2 : 1));
    return shiftDate(date);
}

function isValidDateParam(value: string | null): value is string {
    if (!value || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return false;
    const date = new Date(value);
    return !Number.isNaN(date.getTime()) && shiftDate(date) === value;
}
